### ISSUE TITLE
Lazy Loading?

### ISSUE THREAD

**Issue by junerockwell** [jldec/marked-images#2]
Just wondering, does `marked-images` already support lazy loading images?

**Comment by fmc-gh** [comment]
No, unfortunately nothing like that yet. Good thinking though... 👍 

I've also been wondering about supporting something like [cloudflare images](https://developers.cloudflare.com/images/cloudflare-images/serve-images).

**Comment by junerockwell** [comment]
Support for Cloudflare Images does sound awesome and can be convenient.

But if some images are going to be kept locally for static sites and won't need image servers like Cloudflare, it'd be awesome to lazy load them.

**You can also try supporting NextJS Image as it already has built-in lazy loading https://nextjs.org/docs/basic-features/image-optimization**

Thanks!

**Comment by fmc-gh** [comment]
> You can also try supporting NextJS Image as it already has built-in lazy loading https://nextjs.org/docs/basic-features/image-optimization

I like that suggestion even more - thanks @junerockwell
